apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-persistent-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 25Gi